### ISSUE TITLE
For example, if “tomato” and “tomato sauce” are both in the list, it’s impossible to tag “tomato sauce”.

### ISSUE THREAD

**Issue by ljw9611** [jcubic/tagger#11]
This is great but one issue is that if there are two similar phrases in the completion list then the first tag automatically binds before the user has a chance to finish typing the second phrase. For example, if “tomato” and “tomato sauce” are both in the list, it’s impossible to tag “tomato sauce”. Is there a way around this?

**Comment by jcubic** [comment]
This is a bug, it should detect of there are more than one element in the list and if that element have space if this is the case automatic space should be disabled.

**Comment by ljw9611** [comment]
Thank you for your answers.                        
Auto Space is disabled, but the same problem occurs.
If there are two similar phrases in the full list, the first tag is not bound automatically before the user enters the second phrase.

For example, if both "foo" and "foobar" are on the complete list, 
You try to type "foobar", but a "foo" tag is created before you enter all "foobar".

I would appreciate it if you could suggest a way to solve this problem.

**Comment by jcubic** [comment]
I need to fix this in the code, it's a bug. It should not create tag if more than one element match.

**Comment by ljw9611** [comment]
I've tried many things, but they haven't been solved yet. I would appreciate it if you let me know which part of the code I need to change.

**Comment by jcubic** [comment]
I'm not 100% sure but I think that you would need to modify function `_tag_selected` and check if there are only one match.
But you will also need to handle casewhen someone would like to pick shorter tag, I'm not sure how. Maybe with coma.

**Comment by jcubic** [comment]
Finally found some free time to fix this issue.
