### ISSUE TITLE
Values Not Adding to main Input Field

### ISSUE THREAD

**Issue by ghost** [jcubic/tagger#13]
Hi @jcubic ,

When we type in the field and without pressing comma /enter/space directly taking mouse out of the field then its not appending the value to main input as well its not getting convert like tag.

I tried to add the event on blur form tagger-new input but while firing keypress event, its not allowing because main field converting to hidden/readonly .

![image](https://user-images.githubusercontent.com/22079296/107631264-b1d8e380-6c8a-11eb-9d4e-c3b56c7c0898.png)

**Comment by jcubic** [comment]
I've added new option `add_on_blur` it will make tagger add tags when anything is left in input as tag.

**Comment by sunil209** [comment]
Hi @jcubic , Thanks for above enhancement!

**Comment by jcubic** [comment]
Just published to npm.
