### ISSUE TITLE
Create ReactJS example

### ISSUE THREAD

**Issue by jcubic** [jcubic/tagger#16]
Create an example of using the library in ReactJS and add it into the README.

**Comment by jatnnik** [comment]
Hi, can I work on that?

**Comment by jcubic** [comment]
@wh1zk1d yes go ahead.

**Comment by jatnnik** [comment]
@jcubic Great. Could you please assign me?

**Comment by jatnnik** [comment]
@jcubic Hi, I opened a PR #17
