### ISSUE TITLE
fix the h1 "tagger example" the to be mobile responsive

### ISSUE THREAD

**Issue by MaguiRocha** [jcubic/tagger#33]
It will be a pleasure for me to improve the style of this title.
and also it will be an opportunity for me to improve my skills in css

I send you a screenshot of the error

![bug tagger demo](https://user-images.githubusercontent.com/111162805/196049553-ac59f77d-e2dc-45e8-a06f-2886cab63ac6.png)

Thanks!

**Comment by jcubic** [comment]
1. Thanks, but I don't see a reason to style the demo page. It showcases the component the reset is irrelevant.
2. I don't understand how you can make more responsive RAW HTML, HTML is responsive by design.
3. I have no idea what you want to fix.

**Comment by MaguiRocha** [comment]
the title has no left border
I'm sorry, maybe I expressed myself wrong

But there's no problem! Cheers !
