### ISSUE TITLE
Limit number of tags to given set of tags

### ISSUE THREAD

**Issue by rouilj** [jcubic/tagger#34]
How can I limit the tags that are inserted? Do I need to redefine add_tag(string) somehow to
verify that the tag matches an existing tag?

Thanks.

**Comment by jcubic** [comment]
There is `tag_limit` option in the README. By default, it's set to -1 which means no tag limit.

But if you mean to limit to a list of tags, then there is no such option.

**Comment by rouilj** [comment]
Sorry, I must not have been clear. I don't want to limit the number of tags, I want to validate the tag.

E.G. I have a remote database with a list of valid tags or the completion list has the values:

 ['a', 'b', 'c', 'd']

The user must not be able to enter a tag for 'e', or 'c2'.

**Comment by jcubic** [comment]
As I've said in the second sentence, there is no way right now to do this. You will need to add an option, to limit only to listed tags, and it is probably a good idea to also add a validator function.

Do you want to contribute?

**Comment by rouilj** [comment]
Sorry missed the second sentence. Thanks for the invite to contribute, but my ts knowledge is zero. Setting up a dev environment is not something I have time or knowledge to do. Also at best I have minimal javascript skills, so even
trying to develop it in js would be out of my skillset.

Best of luck with tagger. I'll keep an eye on it but look for some other library to fill my immediate need.

Feel free to close if you don't plan on implementing this at some point.
