### ISSUE TITLE
Wrap modes put input into second line

### ISSUE THREAD

**Issue by jcubic** [jcubic/tagger#37]
I'm not sure why this is happening, but wrap mode makes the input that is min-width: 40px go to the second line. It should fit into the first line unless the text doesn't fit.

![Przechwycenie obrazu ekranu_2023-05-20_13-46-23](https://github.com/jcubic/tagger/assets/280241/bed8951d-9a4a-4c7e-b42a-f39779178a05)

https://codepen.io/jcubic/pen/YbYpqO?editors=1010

**Comment by afaqalii** [comment]
Hello I have fixed the issue. It is due to "justify-content: Star;" I am sharing the 40 seconds video where I first show you the problem and then fixed it and it only breaks the line only when the text does not fit.
[https://www.awesomescreenshot.com/video/17584579?key=398ec3bfd1a8e3474a3ee31f06052824](url)

**Comment by afaqalii** [comment]
paste this video URL to watch the video

**Comment by lucasnetau** [comment]
@jcubic I think this is more an issue with Firefox not shrinking inputs in a Flexbox. The codepen works correctly in Safari and Chrome. https://bugzilla.mozilla.org/show_bug.cgi?id=1242914

A further look is that Firefox sets the input's size property to a default of 20 which sets the minimum size of the input, overflowing the container and wrapping. Adding size="1" to the input fixes the issues. I'll do some tests on the other browsers then raise a PR

**Comment by jcubic** [comment]
The screenshot is from Google Chrome but on Linux.

**Comment by jcubic** [comment]
It seems that adding:

```css
.tagger .tagger-new {
    width: 1px;
}
```
solves the issue.
