### ISSUE TITLE
Limiting the number of tags

### ISSUE THREAD

**Issue by rdetert** [jcubic/tagger#8]
Is there an easy way to limit the number of tags? I'd like users to be able to only enter 5 tags.

**Comment by jcubic** [comment]
No, there is no option like that but it would be easy to add.

**Comment by jcubic** [comment]
It's been a while but I've just add this feature. There is option `tag_limit` if it's positive and non zero it limit the number of tags.
It also disable the input you can type new tag you can only press backspace to remove old tags when tag limit is reached.
